
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fabricio 
  password: PostgreSQL_Role_Password

development:
  <<: *default
  database: app_virtual_store_development
  
test:
  <<: *default
  database: app_virtual_store_test

production:
  <<: *default
  database: app_virtual_store_production
  username: app_virtual_store
  password: <%= ENV['APP_VIRTUAL_STORE_DATABASE_PASSWORD'] %>
